main.o: main.cc Title.o Snake.o
	g++ -g -std=c++17 -c main.cc -lncurses 
Title.o:
	g++ -g -std=c++17 -c Title.cc -lncurses
Snake.o:
	g++ -g -std=c++17 -c Snake.cc -lncurses
clean:
	        rm -f a.out core *.o
			
